package org.example.properties;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

public class StorePropertiesExample {
    public static void main(String[] args) {
        Properties props = new Properties();
        // load baseline from classpath if available
        try (InputStream in = StorePropertiesExample.class.getResourceAsStream("/config.properties")) {
            if (in != null) props.load(in);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        // mutate
        props.setProperty("app.version", String.valueOf(System.currentTimeMillis()));
        props.setProperty("stored.by", "StorePropertiesExample");

        try {
            Path out = Path.of("target/generated-config.properties");
            Files.createDirectories(out.getParent());
            try (FileOutputStream fos = new FileOutputStream(out.toFile())) {
                props.store(fos, "Generated by StorePropertiesExample");
            }
            System.out.println("Wrote properties to: " + out.toAbsolutePath());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}

