spring:
  datasource:
    url: jdbc:postgresql://db:5432/dungeon
    username: dungeon
    password: dungeon
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

experiment:
  split:
    A: 0.5
    B: 0.3
    C: 0.2
