version: "3.9"
services:
  db:
    image: postgres:17
    container_name: dungeon-db
    environment:
      POSTGRES_DB: dungeon
      POSTGRES_USER: dungeon
      POSTGRES_PASSWORD: dungeon
    ports:
      - "5432:5432"
    volumes:
      - dungeon-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dungeon"]
      interval: 5s
      retries: 5

  app:
    build: .
    container_name: dungeon-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
    depends_on:
      db:
        condition: service_healthy

volumes:
  dungeon-data:
